config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'rooms/search'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  get 'users/mypage' => 'users#mypage'
  resources :rooms do
    resources :reservations
  end
  post 'reservation/confirm' => 'reservations#confirm'
  post 'rooms/:room_id/reservations' => 'reservations#create'
  get 'rooms/:room_id/reservations/:id/edit' => 'reservations#edit'
  delete 'rooms' => 'rooms#destroy'
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reserved_rooms, through: :reservations, source: :room
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  def new
    super
  end

  #POST /resource
  def create
    super
  end

  #GET /resource/edit
  def edit
    super
  end

  #PUT /resource
  def update
    super
  end

  #DELETE /resource
  def destroy
    super
  end

  #GET /resource/cancel
  #Forces the session data which is usually expired after sign
  #in to be expired now. This is useful if the user wants to
  #cancel oauth signing in/up in the middle of the process,
  #removing all OAuth session data.
  def cancel
    super
  end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  #If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  #The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  #The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:mypage]

  def mypage
    @user = current_user
    @avatar = current_user.avatar
  end

  def index
    @users = User.all
    @rooms = Room.where(user_id: current_user.id).includes(:user).order("created_at DESC")
    @reservations = Reservation.where(user_id: current_user.id).includes(:user).order("created_at DESC")
  end

  def show
    @user = current_user
    @avatar = current_user.avatar
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "プロフィールを更新しました"
      redirect_to :users_mypage
    else
      flash.now[:alert] = "プロフィールを更新できませんでした"
      render :users_mypage
    end

  end


  def updated_at
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :encrypted_password, :introduction, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/error", obj: @user %>
<div class = "box">
<div class = "box-inner">
<%= form_with model: @user, url: user_path do |f| %>
<h2>プロフィールの編集</h2>
    <%= f.hidden_field :user_id, value: current_user.id %>
        <div class = "profile-avatar">
            <p><%= f.label :avatar ,"アイコン画像" %></p>
            <p><%= f.file_field :avatar %></p>
            <%= f.hidden_field :avatar_cache %>
        </div>
        <div class = "profile-name">
            <p><%= f.label :name ,"名前" %></p>
            <p><%= f.text_field :name %></p>
        </div>

        <div class = "profile-introduction">
            <p><%= f.label :introduction ,"自己紹介" %></p>
            <p><%= f.text_field :introduction %></p>
        </div>
    <div class = "box-buttons">
        <p><%= f.submit "編集を保存する" %></p>
        <p><%= link_to "戻る", :back %></p>
    </div>
    </div>
    </div>
<% end %>

app/views/users/mypage.html.erb
<div class = "setting">
    <div class = "setting-side">
        <h1>設定</h1>
            <div class = "link-box">
                <p><%= link_to "アカウント", user_path(current_user) %></p>
                <p><%= link_to "プロフィール",users_mypage_path(current_user) %></p>
            </div>
    </div>

    <div class = "setting-contents">
        <h2>プロフィール</h2>
        <p class = "edit-link"><%= link_to "編集", edit_user_path(current_user) %></p>
            <div class = "account-informations">
                <div class = "account-information">アイコン画像
                    <p class = "account-information-value"><%= image_tag @user.avatar.url %></p>
                </div>
                <div class = "account-information">名前
                    <p class = "account-information-value"><%= @current_user.name %></p>
                </div>
                <div class = "account-information">紹介文
                    <p class = "account-information-value"><%= @current_user.introduction %></p>
                </div>
            </div>
    </div>
</div>

app/views/users/show.html.erb
<div class = "setting">
    <div class = "setting-side">
        <h1>設定</h1>
        <div class = "link-box">
            <p><%= link_to "アカウント", user_path(current_user) %></p>
            <p><%= link_to "プロフィール",users_mypage_path(current_user) %></p>
        </div>
    </div>
    <div class = "setting-contents">
        <h2>アカウント情報</h2>
        <p class = "edit-link"><%= link_to "編集", [:edit_user_registration] %></p>
            <p>メールアドレス<%= @user.email %></p>
            <p>パスワード<span>********</span></p>
    </div>
</div>