config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'rooms/search'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  get 'users/mypage' => 'users#mypage'
  resources :rooms do
    resources :reservations
  end
  post 'reservation/confirm' => 'reservations#confirm'
  post 'rooms/:room_id/reservations' => 'reservations#create'
  get 'rooms/:room_id/reservations/:id/edit' => 'reservations#edit'
  delete 'rooms' => 'rooms#destroy'
  resources :users
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_search.html.erb
    <%= search_form_for @q, url: rooms_search_path do |f| %>
        <div class = "partial-search-wrapper">
            <div class="partial-search-content">
                <%= f.label :name_or_introduction_cont, 'フリーワード検索', class: 'freeword-search' %>
                <%= f.search_field :name_or_introduction_cont, placeholder: 'キーワード名を入力', class:"partial-search-form-control" %>
                <%= f.label :address_cont, 'エリア検索', class: 'area_search'%>
                <%= f.search_field :address_cont, placeholder: 'エリア名を入力', class:'partial-search-form-control'%>
            </div>
            <div class="partial-search-content">
                <%= f.submit 'この条件で検索する', class:"partial-search-btn" %>
            </div>
        </div>
    <% end %>