config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'rooms/search'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  get 'users/mypage' => 'users#mypage'
  resources :rooms do
    resources :reservations
  end
  post 'reservation/confirm' => 'reservations#confirm'
  post 'rooms/:room_id/reservations' => 'reservations#create'
  get 'rooms/:room_id/reservations/:id/edit' => 'reservations#edit'
  delete 'rooms' => 'rooms#destroy'
  resources :users
end

app/models/room.rb
class Room < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["name", "address","introduction"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["reservations", "user"]
    end

    mount_uploader :img, ImgUploader
    belongs_to :user
    has_many :reservations, dependent: :destroy
    
    validates :name,presence: true
    validates :introduction,presence: true
    validates :price,presence: true
    validates :address,presence: true

    def reserved_by?(user)
        reservations.where(user_id:user.id).exsists?
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_q, only: [:index, :show]

  def index
    @user = current_user
    @rooms = Room.where(user_id: current_user.id).includes(:user).order("created_at DESC")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "施設を登録しました"
      redirect_to :rooms
    else
      flash.now[:alert] = "施設を登録できませんでした"
      render "new"
    end
  end

  def show
    @reservation = Reservation.new
    @room = Room.find(params[:id])
    @user = User.find(current_user.id)
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "施設情報を更新しました"
      redirect_to rooms_url
    else
      flash.now[:alert] = "施設情報を更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash.now[:notice] = "施設を削除しました"
    redirect_to :rooms
  end

  def search
    @rooms = Room.includes(:user).order('created_at DESC')
    @q = Room.ransack(params[:q])
    @results = @q.result(distinct: true).page(params[:page]).per(8).order('created_at DESC')
  end

  private

  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :user_id, :img, :img_cache, :reservation_id)
  end

  def set_q
      @q = Room.ransack(params[:q])
      @search_room = @q.result(distinct: true).order(created_at: "DESC").includes(:user).page(params[:page]).per(4)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%= render "shared/error", obj: @room %>
<div class = "box">
    <div class = "box-inner">
        <h2>施設の編集</h2>
        <%= form_with model: @room, url: room_path do |f| %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <div class = "field">
            <%= f.label :name ,"施設名" %>
            <%= f.text_field :name %>
        </div>
        <div class = "field">
            <%= f.label :introduction ,"施設詳細" %>
            <%= f.text_field :introduction %>
        </div>
        <div class = "field">
            <%= f.label :price ,"料金" %>
            <%= f.text_field :price %>
        </div>
        <div class = "field">
            <%= f.label :address ,"住所" %>
            <%= f.text_field :address %>
        </div>
        <div class = "field">
            <%= f.label :img ,"施設画像" %>
            <%= f.file_field :img %>
            <%= f.hidden_field :img_cache %>
        </div>
        <div class = "box-buttons">
            <%= link_to "キャンセル", :rooms %>
            <%= f.submit "編集を保存する" %>
        </div>
        <% end %>
    </div>
</div>

app/views/rooms/index.html.erb
<h2>登録済み施設一覧</h2>
<%= link_to "施設の新規登録" ,[:new_room]%>
    <table>
        <thead>
            <tr class = "room-nav">
                <th class = "room-image-title">画像</th>
                <th>施設名</th>
                <th>紹介文</th>
                <th>料金</th>
                <th>作成日</th>
            </tr>
        </thead>

        <tbody class = "room-index">
            <% @rooms.each do |room| %>
            <tr><%= hidden_field_tag :room_id, @room_id %>
                <td><%= image_tag room.img.url, alt: "施設画像", class: "room-image" %></td>
                <td><%= link_to room.name , room %></td>
                <td><%= room.introduction %></td>
                <td><%= number_to_currency(room.price, :unit => "¥", :format => "%u%n") %></td>
                <td><%= room.created_at.to_s(:datetime_jp) %></td>
                <td><%= link_to"編集", edit_room_path(room.id) %></td>
                <td><%= button_to"削除", room_path(room.id), method: :delete, data:{confirm:"施設を削除しますか？"} %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    

app/views/rooms/new.html.erb
<%= render "shared/error", obj: @room %>
<div class = "box">
    <div class = "box-inner">
        <h2>施設の新規登録</h2>
        <%= form_with model: @room do |f| %>
        <div class = "field">
            <%= f.label :name ,"施設名" %>
            <%= f.text_field :name %>
        </div>
        <div class = "field">
            <%= f.label :introduction ,"施設詳細" %>
            <%= f.text_field :introduction %>
        </div>
        <div class = "field">
            <%= f.label :price ,"料金" %>
            <%= f.text_field :price %>
        </div>
        <div class = "field">
            <%= f.label :address ,"住所" %>
            <%= f.text_field :address %>
        </div>
        <div class = "field">
            <%= f.label :img ,"施設画像" %>
            <%= f.file_field :img %>
            <%= f.hidden_field :img_cache %>
        </div>
        <div class = "box-buttons">
            <%= link_to "キャンセル", :rooms %>
            <%= f.submit "保存" %>
        </div>
        <% end %>
    </div>
</div>

app/views/rooms/search.html.erb
<p><%= render "shared/search"%></p>

<div class = "search-container">
    <h3>検索結果一覧</h3>
        <div class = "search-results">
            <% if @results.present? %>
                <h4>検索結果：<%= @results.count %>件</h4>
                    <div class = "room-container">
                        <% @results.each do |room| %>
                        <ul class = "room-list">
                            <li class = "image"><%= image_tag room.img.url,size: "350x250" %></li>
                            <li class = "room-name"><%= room.name %></li>
                            <li><%= room.address %></>
                            <li><%= room.introduction.truncate(30) %></li>
                            <li class = "price"><%= number_to_currency(room.price, :unit => "¥", :format => "%u%n") %></li>
                            <li><%= link_to "詳細はこちら", room_path(room.id),class:"btn btn-warning" %><td>
                        </ul>
                        <% end %>
                    </div>
            <% else %>
                <h4>検索結果0件</h4>
            <% end %>
        </div>
</div>

app/views/rooms/show.html.erb
<p><%= render "shared/search"%></p>
<div class = "room-show">
    <h2>施設詳細</h2>   
    <%= link_to "戻る", :back %>
    <%= form_with model: @room do |f| %>
    <table>
        <tr>
            <th><%= f.label :img ,"施設画像" %></th>
            <td><%= image_tag @room.img.url %></td>
        </tr>
        <tr>
            <th><%= f.label :name ,"施設名" %></th>
            <td><%= @room.name %></td>
        </tr>
        <tr>
            <th><%= f.label :introduction ,"施設詳細" %></th>
            <td><%= @room.introduction %></td>
        </tr>
        <tr>
            <th><%= f.label :price ,"料金" %></th>
            <td class = "room-show-price"><%= number_to_currency(@room.price, :format=> "%u%n", :unit => "¥") %></td>
        </tr>
        <tr>
            <th><%= f.label :address ,"住所" %></th>
            <td><%= @room.address %></td>
        </tr>
    </table>
    <div class = "hidden">
        <% f.hidden_field :user_id, value: @user_id %>
        <% f.hidden_field :room_id, value: @room_id %>
    </div>
    <div class = "reserve-button">
        <%= link_to "予約する" , new_room_reservation_path(room_id: @room.id,user_id: current_user),class:"btn btn-warning" %>
    </div>
<% end %>
</div>