config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'rooms/search'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  get 'users/mypage' => 'users#mypage'
  resources :rooms do
    resources :reservations
  end
  post 'reservation/confirm' => 'reservations#confirm'
  post 'rooms/:room_id/reservations' => 'reservations#create'
  get 'rooms/:room_id/reservations/:id/edit' => 'reservations#edit'
  delete 'rooms' => 'rooms#destroy'
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>宿泊予約システム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    
  </head>

  <body>
    <header class = "header">
    <a class = "logo" href = "/">Potepan Share</a>
    <ul class = "login_signup">
      <% if user_signed_in? %>
        <li><%= image_tag current_user.avatar.url, class: "avatar" %></li>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><%= link_to "施設の新規登録",  new_room_path, class:"dropdown-item" %></li>
              <li><%= link_to "予約済み施設一覧", room_reservations_path(current_user.reservations), class:"dropdown-item" %></li>
              <li><%= link_to "登録済み施設一覧", rooms_path(current_user.rooms), class:"dropdown-item" %></li>
              <li><%= link_to "アカウント設定", users_mypage_path(current_user), class:"dropdown-item" %></li>
              <li><%= button_to "ログアウト", destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
            </ul>
        </div>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </ul>
    </header>
    <div class="text-success">
      <%= flash[:notice] %>
    </div>
    <div class="text-danger">
      <%= flash[:alert] %>
    </div>
  
    <%= yield %>

    <footer>
      <div class = "footer_logo">Potepan Share</div>
      <p class = "copyright">Copyright © Potepan Share 2023 All rights reserved</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>